setwd("/opt/tensiobot/analisis/")
library("xlsx")
path <- "./bbdd.xlsx"
pacientes <-read.xlsx(path, "pacientes", header=TRUE, colClasses=NA)
summary(pacientes)
CheckList <-read.xlsx(path, "Check list", header=TRUE, colClasses=NA)
summary(CheckList)
MAPA <-read.xlsx(path, "MAPA", header=TRUE, colClasses=NA)
summary(MAPA)
AMPA <-read.xlsx(path, "AMPA", header=TRUE, colClasses=NA)
summary(AMPA)
Satisfaccion <-read.xlsx(path, "Satisfaccion", header=TRUE, colClasses=NA)
summary(Satisfaccion)
Farmacos <-read.xlsx(path, "Farmacos", header=TRUE, colClasses=NA)
summary(Farmacos)
AMPA_MEDIAS <-read.xlsx(path, "AMPA_medias", header=TRUE, colClasses=NA)
summary(AMPA_MEDIAS)
Analisis1 <- read.xlsx(path, "PacMAPA_AMPA", header=TRUE, colClasses=NA)
summary(Analisis1)
FarmacosPaciente <- read.xlsx(path, "FarmacosPaciente", header=TRUE, colClasses=NA)
summary(FarmacosPaciente)
ChecklistCompleto <- read.xlsx(path, "ChecklistCompleto", header=TRUE, colClasses=NA)
summary(ChecklistCompleto)
table(Farmacos$Farmaco)

# Resultados descriptivos por grupos

by( Analisis1$Edad , Analisis1$grupo, summary)
by( Analisis1$IMC , Analisis1$grupo, summary)
by( Analisis1$creatinina..mg.d , Analisis1$grupo , summary)
by( Analisis1$glucosa.mg.gl , Analisis1$grupo, summary)
by( Analisis1$albuminuria.mg.g , Analisis1$grupo, summary)
round(prop.table (table (Analisis1$sexo, Analisis1$grupo),margin=2)*100, digits=1)

round(prop.table (table (Analisis1$Situacion.laboral , Analisis1$grupo),margin=2)*100, digits=1)
round(prop.table (table (Analisis1$Nivel.de.estudios , Analisis1$grupo),margin=2)*100, digits=1)
round(prop.table (table (Analisis1$Diagnostico , Analisis1$grupo),margin=2)*100, digits=1)
round(prop.table (table (Analisis1$diabetes , Analisis1$grupo),margin=2)*100, digits=1)
round(prop.table (table (FarmacosPaciente$Farmaco , FarmacosPaciente$grupo),margin=2)*100, digits=1)
round(prop.table (table (FarmacosPaciente$NumFarmacos , FarmacosPaciente$grupo),margin=2)*100, digits=1)
round(prop.table (table (FarmacosPaciente$GrupoTer , FarmacosPaciente$grupo),margin=2)*100, digits=1)

round(prop.table () ,margin=2)*100, digits=1)

